// This script is designed to test the solidity smart contract - SuppyChain.sol -- and the various functions within
// Declare a variable and assign the compiled smart contract artifact
const SupplyChain = artifacts.require('SupplyChain');

contract('SupplyChain', function(accounts) {
    // Declare few constants and assign a few sample accounts generated by ganache-cli
    const ownerID = accounts[0];
    const newOwner = accounts[9]

    console.log("ganache-cli accounts used here...")
    console.log("Contract Owner: accounts[0] ", accounts[0])
    
    // 1st Test
    it("Testing transferOwnership by transferring the ownership of contract", async() => {
        const supplychain = await SupplyChain.deployed();
        
        //Perform the transfer of ownership
        await supplychain.transferOwnership(newOwner);
        
        // check the owner
        assert.equal(await supplychain.isOwner.call({from : newOwner}) , true, 'Owner not updated after transferOwnership')        
    })    

    // 2nd Test
    it("Testing renounceOwnership by removing the ownership of contract", async() => {
        const supplychain = await SupplyChain.deployed();
        
        //Perform the removal of ownership
        await supplychain.renounceOwnership({from: newOwner});
        
        // check the owner
        assert.equal(await supplychain.isOwner.call({from : newOwner}) , false, 'Owner not removed after renounceOwnership')        
    })    


});

